### PR TITLE
chore: install validator and improve eslint to work with express.js

### PR DESCRIPTION
**Pull request by AdrianValdes**
Hi @chmette,

This is going to be big because the error handler is quite different, I am going to try to split it on different commits if the code let's me.

### CODE REVIEW

**Comment by AdrianValdes** [comment]
Still less than 150 lines of code... Ok.

**Review by chmette — COMMENTED** [review]
if i log in with a wrong mail i get : Request failed with status code 401
log in with wrong password: i ll be logged in

**Comment by AdrianValdes** [comment]
> if i log in with a wrong mail i get : Request failed with status code 401
log in with wrong password: i ll be logged in 

You need the updated client

**Comment by chmette** [comment]
i tested in insomnia completely and there its all good now , and it works really good

**Review by chmette — APPROVED** [review]
it works really good in in the BackEnd with  insomnia

**Comment by AdrianValdes** [comment]
> it works really good in in the BackEnd with insomnia

It will be good to have this pattern here and practice it. We can always come back and reuse it changing what we need.

**Pull request merged**
