### PR TITLE
Create node.js.yml

### PR DESCRIPTION
**Pull request by chmette**
Add workflow analog records-client

### CODE REVIEW

**Comment by AdrianValdes** [comment]
Hi @chmette;
Check this out: pm ERR! The `npm ci` command can only install with an existing package-lock.json

You are running `npm run lint` but haven't set any script for that in the package.json

Also, try to wait until all checks pass before asking for the review ;)

**Comment by AdrianValdes** [comment]
Also, let's solve one PR by one, it is better than making several PR at once, the code get's messy in git.

**Comment by chmette** [comment]
i insert the script.
now i know that there is a connection :) already learned :)

**Comment by AdrianValdes** [comment]
> i insert the script.
now i know that there is a connection :) already learned :)

All good, now we have to take care of the PRs being sync, because  I you merge the other branch this one is going to be moved in time, check this out:
image

So it can introduce breaking issues, it doesn't have too, I am just bring it up so you have it in mind. Now you have several options, you could delete this PR and make another PR after you merge to main and pull, or you can merge the other branch and try to fix this PR here, but remember we don't merge if all the checks are not passing, so you have to fix that here. I will let you decide what you think is best.

**Pull request closed without merging**
